### ISSUE TITLE
金融通识-第三章-复习题第二题

### ISSUE THREAD

**Issue by starts-mxy** [FinTechCourse2019/Course#6]
在出售证券时与购买者约定到期买回证券的方式，我理解应该是买断式回购。质押式回购只是抵押，资金融出方并不能对抵押权做任何操作。 如果笼统的只是协议回购的话，那么感觉证券发行好像也可以这么理解。债券发行出来，投资者购买，到期，兑付，是不是也属于出售证券，到期购回。

**Comment by FinTechCourse2019** [comment]
你的意思是没有可选答案？

**Comment by FinTechCourse2019** [comment]
咨询过老师
答案 ： D

可参考书本 P36
（四） 回购协议市场 内容

**Comment by FinTechCourse2019** [comment]
可参考书本 P36
（四） 回购协议市场 内容
